### ISSUE TITLE
Unable to install v2.0

### ISSUE THREAD

**Issue by egemon** [fivetanley/ember-cli-dotenv#40]
`ember install ember-cli-dotenv@^2.0.0   `
```
Command failed: yarn add --dev ember-cli-dotenv@^2.0.0 --non-interactive
error Couldn't find any versions for "ember-cli-dotenv" that matches "^2.0.0"

yarn add v1.3.2
[1/5] Validating package.json...
[2/5] Resolving packages...
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

Error: Command failed: yarn add --dev ember-cli-dotenv@^2.0.0 --non-interactive
error Couldn't find any versions for "ember-cli-dotenv" that matches "^2.0.0"

yarn add v1.3.2
[1/5] Validating package.json...
[2/5] Resolving packages...
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

    at Promise.all.then.arr (/home/user/projects/app/node_modules/execa/index.js:231:11)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

**Comment by SergeAstapov** [comment]
@egemon yeah, version 2.0 wasn't published to npm yet as we need original author for that.
See #30 for background and history.
Could you please do `ember install fivetanley/ember-cli-dotenv#master` for now?

**Comment by SergeAstapov** [comment]
Version 2.0 has been published to npm.
