### ISSUE TITLE
Started getting this.ui.warn error since yesterday

### ISSUE THREAD

**Issue by JibranKalia** [fivetanley/ember-cli-dotenv#52]
```
TypeError: this.ui.warn is not a function
TypeError: this.ui.warn is not a function
    at keys.reduce (/var/lib/jenkins/workspace/.../node_modules/ember-cli-dotenv/index.js:100:19)
    at Array.reduce (native)
    at Class._pickConfigKeys (/var/lib/jenkins/workspace/.../node_modules/ember-cli-dotenv/index.js:94:17)
    at Class.config (/var/lib/jenkins/workspace/.../node_modules/ember-cli-dotenv/index.js:70:17)
    at addons.reduce (/var/lib/jenkins/workspace/.../node_modules/ember-cli/lib/models/project.js:302:31)
    at Array.reduce (native)
    at Project.getAddonsConfig (/var/lib/jenkins/workspace/Portal Deploy BETA/node_modules/ember-cli/lib/models/project.js:300:24)
    at Project.configWithoutCache (/var/lib/jenkins/workspace/.../node_modules/ember-cli/lib/models/project.js:251:31)
    at Project.config (/var/lib/jenkins/workspace/.../node_modules/ember-cli/lib/models/project.js:234:16)
    at Class.included (/var/lib/jenkins/workspace/.../node_modules/ember-browserify/lib/index.js:39:38)Pipeline aborted
```

**Comment by SergeAstapov** [comment]
@JibranKalia 2.2.1 has been published with fix.
